/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseLayer.DB_connection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class Part_Suppliers extends javax.swing.JFrame {

	String curruntSupplierId;

	public Part_Suppliers() {
		initComponents();
		loadPartSuppliers();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        IconMinMaxClose = new javax.swing.JPanel();
        ButtonClose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Close1 = new javax.swing.JLabel();
        Close2 = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        FullMax = new javax.swing.JLabel();
        FullMax1 = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuHide = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        lblRepairJobs = new javax.swing.JLabel();
        AddProduct = new javax.swing.JPanel();
        lblRestorationJobs = new javax.swing.JLabel();
        EditProduct = new javax.swing.JPanel();
        lblSpareParts = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblPartSuppliers = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblEmployees = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblContactCustomers = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblReports = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblPurchaseParts = new javax.swing.JLabel();
        DashBoard = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPaneManProducts = new javax.swing.JScrollPane();
        jTablepro = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        lblSizeMan = new javax.swing.JLabel();
        txtCompantName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblBrandNameMan1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtSupplierEmailSearch = new javax.swing.JTextField();
        lblProductIDMan6 = new javax.swing.JLabel();
        lblBrandNameMan2 = new javax.swing.JLabel();
        lblBrandNameMan3 = new javax.swing.JLabel();
        txtTPNo = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(79, 78, 78));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        IconMinMaxClose.setBackground(new java.awt.Color(61, 61, 61));
        IconMinMaxClose.setPreferredSize(new java.awt.Dimension(150, 50));

        ButtonClose.setBackground(new java.awt.Color(79, 78, 78));
        ButtonClose.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonClose.setLayout(new java.awt.BorderLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelW.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        ButtonClose.add(Close, java.awt.BorderLayout.CENTER);

        Close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close1MouseExited(evt);
            }
        });
        ButtonClose.add(Close1, java.awt.BorderLayout.CENTER);

        Close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelW.png"))); // NOI18N
        Close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close2MouseExited(evt);
            }
        });
        ButtonClose.add(Close2, java.awt.BorderLayout.CENTER);

        ButtonMax.setBackground(new java.awt.Color(79, 78, 78));
        ButtonMax.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonMax.setLayout(new java.awt.BorderLayout());

        FullMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MaxW.png"))); // NOI18N
        FullMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FullMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullMaxMouseExited(evt);
            }
        });
        ButtonMax.add(FullMax, java.awt.BorderLayout.CENTER);

        FullMax1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MaxW.png"))); // NOI18N
        FullMax1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullMax1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FullMax1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullMax1MouseExited(evt);
            }
        });
        ButtonMax.add(FullMax1, java.awt.BorderLayout.CENTER);

        ButtonMin.setBackground(new java.awt.Color(79, 78, 78));
        ButtonMin.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minW.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        ButtonMin.add(jLabel4, java.awt.BorderLayout.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minW.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel8.setPreferredSize(new java.awt.Dimension(1366, 768));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        ButtonMin.add(jLabel8, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout IconMinMaxCloseLayout = new javax.swing.GroupLayout(IconMinMaxClose);
        IconMinMaxClose.setLayout(IconMinMaxCloseLayout);
        IconMinMaxCloseLayout.setHorizontalGroup(
            IconMinMaxCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconMinMaxCloseLayout.createSequentialGroup()
                .addComponent(ButtonMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        IconMinMaxCloseLayout.setVerticalGroup(
            IconMinMaxCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ButtonMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Header.add(IconMinMaxClose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setPreferredSize(new java.awt.Dimension(270, 450));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuHide.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        lblRepairJobs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRepairJobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepairJobs.setText("REPAIR JOBS");
        lblRepairJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRepairJobsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRepairJobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRepairJobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductMouseClicked(evt);
            }
        });

        lblRestorationJobs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRestorationJobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestorationJobs.setText("RESTORATION JOBS");
        lblRestorationJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRestorationJobsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddProductLayout = new javax.swing.GroupLayout(AddProduct);
        AddProduct.setLayout(AddProductLayout);
        AddProductLayout.setHorizontalGroup(
            AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRestorationJobs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddProductLayout.setVerticalGroup(
            AddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRestorationJobs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        EditProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProductMouseClicked(evt);
            }
        });

        lblSpareParts.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSpareParts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpareParts.setText("SPARE PARTS");
        lblSpareParts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSparePartsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EditProductLayout = new javax.swing.GroupLayout(EditProduct);
        EditProduct.setLayout(EditProductLayout);
        EditProductLayout.setHorizontalGroup(
            EditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpareParts, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        EditProductLayout.setVerticalGroup(
            EditProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSpareParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logoutLogo.png"))); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPartSuppliers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPartSuppliers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPartSuppliers.setText("PART SUPPLIERS");
        lblPartSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPartSuppliersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPartSuppliersMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPartSuppliers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPartSuppliers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblEmployees.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployees.setText("EMPLOYEES");
        lblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmployees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmployees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblContactCustomers.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblContactCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContactCustomers.setText("CONTACT CUSTOMERS");
        lblContactCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactCustomersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lblContactCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblContactCustomers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblReports.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReports.setText("REPORTS");
        lblReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportsMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblPurchaseParts.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPurchaseParts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPurchaseParts.setText("PURCHASE PARTS");
        lblPurchaseParts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPurchasePartsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPurchaseParts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPurchaseParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuHideLayout = new javax.swing.GroupLayout(MenuHide);
        MenuHide.setLayout(MenuHideLayout);
        MenuHideLayout.setHorizontalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuHideLayout.createSequentialGroup()
                        .addGroup(MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuHideLayout.setVerticalGroup(
            MenuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(AddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(EditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Menu.add(MenuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        DashBoard.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel5.setText("RustRepair Vehical restoration & Repair Center");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(0, 51, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manage Part Suppliers");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPaneManProducts.setBackground(new java.awt.Color(255, 255, 255));

        jTablepro.setAutoCreateRowSorter(true);
        jTablepro.setBackground(new java.awt.Color(204, 204, 204));
        jTablepro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Company Name", "TP NO", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablepro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableproMouseClicked(evt);
            }
        });
        jScrollPaneManProducts.setViewportView(jTablepro);
        if (jTablepro.getColumnModel().getColumnCount() > 0) {
            jTablepro.getColumnModel().getColumn(1).setResizable(false);
            jTablepro.getColumnModel().getColumn(2).setResizable(false);
            jTablepro.getColumnModel().getColumn(3).setResizable(false);
        }

        btnDelete.setBackground(new java.awt.Color(14, 66, 117));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblSizeMan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSizeMan.setText("Company Name :");

        txtCompantName.setBackground(new java.awt.Color(204, 204, 204));
        txtCompantName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompantNameActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(14, 66, 117));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setActionCommand("Add");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblBrandNameMan1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBrandNameMan1.setText("Email :");

        btnAdd.setBackground(new java.awt.Color(14, 66, 117));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtSupplierEmailSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtSupplierEmailSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierEmailSearchActionPerformed(evt);
            }
        });
        txtSupplierEmailSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierEmailSearchKeyReleased(evt);
            }
        });

        lblProductIDMan6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductIDMan6.setText("Search with Supplier Email :");

        lblBrandNameMan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBrandNameMan2.setText("TP NO :");

        lblBrandNameMan3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBrandNameMan3.setText("Address :");

        txtTPNo.setBackground(new java.awt.Color(204, 204, 204));
        txtTPNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTPNoActionPerformed(evt);
            }
        });

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jButton2.setText("Clear All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(508, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblBrandNameMan3)
                                .addGap(54, 54, 54)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblBrandNameMan1)
                                .addGap(74, 74, 74)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSizeMan)
                            .addComponent(lblBrandNameMan2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompantName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTPNo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(300, 300, 300))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblProductIDMan6)
                                .addGap(18, 18, 18)
                                .addComponent(txtSupplierEmailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPaneManProducts))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSizeMan)
                            .addComponent(txtCompantName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(lblBrandNameMan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(lblBrandNameMan3)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBrandNameMan2)
                                .addComponent(txtTPNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductIDMan6)
                    .addComponent(txtSupplierEmailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneManProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1129, Short.MAX_VALUE)
            .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DashBoardLayout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DashBoardLayout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(DashBoard, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1399, 884));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	public void changecolor(JPanel hover, Color rand) {
		hover.setBackground(rand);
	}

	public void clickmenu(JPanel h1, JPanel h2, int numberbool) {
		if (numberbool == 1) {
			h1.setBackground(new Color(176, 176, 176));
			h2.setBackground(new Color(79, 78, 78));
		} else {
			h1.setBackground(new Color(79, 78, 78));
			h2.setBackground(new Color(176, 176, 176));
		}
	}

	public void changeimage(JLabel button, String resourcheimg) {
		ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
		button.setIcon(aimg);
	}

	public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button) {
		if (dashboard == true) {
			menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
			changeimage(button, "/Icon/MenuW.png");
		} else {
			menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
			changeimage(button, "/Icon/HidemenuW.png");
		}
	}


    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
		changecolor(ButtonClose, new Color(176, 176, 176));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
		changecolor(ButtonClose, new Color(79, 78, 78));
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
		System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void FullMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMaxMouseEntered
		changecolor(ButtonMax, new Color(176, 176, 176));
    }//GEN-LAST:event_FullMaxMouseEntered

    private void FullMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMaxMouseExited
		changecolor(ButtonMax, new Color(79, 78, 78));
    }//GEN-LAST:event_FullMaxMouseExited

    private void FullMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMaxMouseClicked
		if (this.getExtendedState() != Part_Suppliers.MAXIMIZED_BOTH) {
			this.setExtendedState(Part_Suppliers.MAXIMIZED_BOTH);
		} else {
			this.setExtendedState(Part_Suppliers.NORMAL);
		}
    }//GEN-LAST:event_FullMaxMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
		try {
			this.setState(ICONIFIED);
		} catch (Exception e) {
		}
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
		changecolor(ButtonMin, new Color(176, 176, 176));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
		changecolor(ButtonMin, new Color(79, 78, 78));
    }//GEN-LAST:event_jLabel4MouseExited

    private void Close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MouseClicked
		System.exit(0);
    }//GEN-LAST:event_Close1MouseClicked

    private void Close1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MouseEntered
		changecolor(ButtonClose, new Color(176, 176, 176));
    }//GEN-LAST:event_Close1MouseEntered

    private void Close1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close1MouseExited
		changecolor(ButtonClose, new Color(79, 78, 78));
    }//GEN-LAST:event_Close1MouseExited

    private void Close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close2MouseClicked
		System.exit(0);
    }//GEN-LAST:event_Close2MouseClicked

    private void Close2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close2MouseEntered
		changecolor(ButtonClose, new Color(176, 176, 176));
    }//GEN-LAST:event_Close2MouseEntered

    private void Close2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close2MouseExited
		changecolor(ButtonClose, new Color(79, 78, 78));
    }//GEN-LAST:event_Close2MouseExited

    private void FullMax1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMax1MouseClicked
		if (this.getExtendedState() != Part_Suppliers.MAXIMIZED_BOTH) {
			this.setExtendedState(Part_Suppliers.MAXIMIZED_BOTH);
		} else {
			this.setExtendedState(Part_Suppliers.NORMAL);
		}
    }//GEN-LAST:event_FullMax1MouseClicked

    private void FullMax1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMax1MouseEntered
		changecolor(ButtonMax, new Color(176, 176, 176));
    }//GEN-LAST:event_FullMax1MouseEntered

    private void FullMax1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullMax1MouseExited
		changecolor(ButtonMax, new Color(79, 78, 78));
    }//GEN-LAST:event_FullMax1MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
		try {
			this.setState(ICONIFIED);
		} catch (Exception e) {
		}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
		changecolor(ButtonMin, new Color(176, 176, 176));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
		changecolor(ButtonMin, new Color(79, 78, 78));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

		int pop = JOptionPane.YES_NO_OPTION;
		int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", pop);
		if (result == 0) {
			this.dispose();
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblSparePartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSparePartsMouseClicked
		Spare_Parts frame = new Spare_Parts();
		frame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_lblSparePartsMouseClicked

    private void AddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductMouseClicked
		// TODO add your handling code here:
    }//GEN-LAST:event_AddProductMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked

		this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void lblRepairJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRepairJobsMouseClicked
		Repair_Jobs frame = new Repair_Jobs();
		frame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_lblRepairJobsMouseClicked

    private void EditProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProductMouseClicked
		// TODO add your handling code here:
    }//GEN-LAST:event_EditProductMouseClicked

    private void lblRestorationJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRestorationJobsMouseClicked
		Restoration_Jobs frame = new Restoration_Jobs();
		frame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_lblRestorationJobsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
		if (txtEmail != null && !txtEmail.getText().equals("0") && !txtEmail.getText().equals("") && txtCompantName != null && !txtCompantName.getText().equals("0") && !txtCompantName.getText().equals("")) {
			try {
				DB_connection.iud("INSERT INTO Part_supplier (Company_name,Email,Tel_number,Address) values ('" + txtCompantName.getText() + "','" + txtEmail.getText() + "','" + txtTPNo.getText() + "','" + txtAddress.getText() + "')");

				JOptionPane.showMessageDialog(this, "Spare Part Supplier Registered.");

				clearAll();
				loadPartSuppliers();

			} catch (Exception ex) {
				ex.printStackTrace();
			}

		} else {
			JOptionPane.showMessageDialog(this, "Please enter All Details.");
		}

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
		try {
			DB_connection.iud("DELETE FROM Part_supplier WHERE idPart_supplier = '"+curruntSupplierId+"'");
			JOptionPane.showMessageDialog(this, "Deleted");
			loadPartSuppliers();
			clearAll();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
		if (txtEmail != null && !txtEmail.getText().equals("0") && !txtEmail.getText().equals("") && txtCompantName != null && !txtCompantName.getText().equals("0") && !txtCompantName.getText().equals("")) {
			try {
				DB_connection.iud("Update Part_supplier SET Company_name = '" + txtCompantName.getText() + "',Tel_number = '" + txtTPNo.getText() + "',Address = '" + txtAddress.getText() + "', Email = '" + txtEmail.getText() + "' WHERE idPart_supplier = '"+curruntSupplierId+"'");

				JOptionPane.showMessageDialog(this, "Details Updated.");

				clearAll();
				loadPartSuppliers();

			} catch (Exception ex) {
				ex.printStackTrace();
			}

		} else {
			JOptionPane.showMessageDialog(this, "Please enter All Details.");
		}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSupplierEmailSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierEmailSearchActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierEmailSearchActionPerformed

    private void txtCompantNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompantNameActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtCompantNameActionPerformed

    private void lblPartSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPartSuppliersMouseClicked
		Part_Suppliers frame = new Part_Suppliers();
		frame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_lblPartSuppliersMouseClicked

    private void lblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeesMouseClicked
		Employees frame = new Employees();
		frame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_lblEmployeesMouseClicked

    private void lblReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseClicked
		try {
			Connection con = DB_connection.getDB();
			ResultSet rs = DB_connection.search("select * from Mechanic_service");
			double i = 0;
			while (rs.next()) {
				i += Double.parseDouble(rs.getString("Total_price"));
			}
			Map m = new HashMap();
			m.put("total", i + "");

			JasperDesign jasdi = JRXmlLoader.load("C:\\monthlyIncome.jrxml");
			String sql = "select * from Mechanic_service";
			JRDesignQuery newQuery = new JRDesignQuery();
			newQuery.setText(sql);
			jasdi.setQuery(newQuery);
			JasperReport js = JasperCompileManager.compileReport(jasdi);
			JasperPrint jp = JasperFillManager.fillReport(js, m, con);
			JasperViewer.viewReport(jp, false);

		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_lblReportsMouseClicked

    private void lblPurchasePartsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchasePartsMouseClicked
		Purchase_Parts frame = new Purchase_Parts();
		frame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_lblPurchasePartsMouseClicked

    private void lblContactCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactCustomersMouseClicked
		Contact_Customers frame = new Contact_Customers();
		frame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_lblContactCustomersMouseClicked

    private void lblReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseEntered
		// TODO add your handling code here:
    }//GEN-LAST:event_lblReportsMouseEntered

    private void txtTPNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTPNoActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtTPNoActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jTableproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableproMouseClicked
		try {
			int i = jTablepro.getSelectedRow();
			curruntSupplierId = (String) jTablepro.getValueAt(i, 0);
			txtEmail.setText((String) jTablepro.getValueAt(i, 1));
			txtCompantName.setText((String) jTablepro.getValueAt(i, 2));
			txtTPNo.setText((String) jTablepro.getValueAt(i, 3));
			txtAddress.setText((String) jTablepro.getValueAt(i, 4));
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_jTableproMouseClicked

    private void txtSupplierEmailSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierEmailSearchKeyReleased
		try {
			if (!txtSupplierEmailSearch.getText().equals("") || txtSupplierEmailSearch.getText() != null) {

				jTablepro.removeAll();
				jTablepro.repaint();
				jTablepro.revalidate();
				DefaultTableModel dtm = (DefaultTableModel) jTablepro.getModel();
				dtm.getDataVector().removeAllElements();
				ResultSet sr = DB_connection.search("select * from Part_supplier where Email like '%" + txtSupplierEmailSearch.getText() + "%'");

				while (sr.next()) {

					Vector v = new Vector();
					v.add(sr.getString("idPart_supplier"));
					v.add(sr.getString("Email"));
					v.add(sr.getString("Company_name"));
					v.add(sr.getString("Tel_number"));
					v.add(sr.getString("Address"));

					dtm.addRow(v);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_txtSupplierEmailSearchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearAll();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblPartSuppliersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPartSuppliersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPartSuppliersMouseEntered

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Part_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Part_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Part_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Part_Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Part_Suppliers().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProduct;
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Close1;
    private javax.swing.JLabel Close2;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JPanel EditProduct;
    private javax.swing.JLabel FullMax;
    private javax.swing.JLabel FullMax1;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel IconMinMaxClose;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuHide;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPaneManProducts;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTablepro;
    private javax.swing.JLabel lblBrandNameMan1;
    private javax.swing.JLabel lblBrandNameMan2;
    private javax.swing.JLabel lblBrandNameMan3;
    private javax.swing.JLabel lblContactCustomers;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JLabel lblPartSuppliers;
    private javax.swing.JLabel lblProductIDMan6;
    private javax.swing.JLabel lblPurchaseParts;
    private javax.swing.JLabel lblRepairJobs;
    private javax.swing.JLabel lblReports;
    private javax.swing.JLabel lblRestorationJobs;
    private javax.swing.JLabel lblSizeMan;
    private javax.swing.JLabel lblSpareParts;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCompantName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSupplierEmailSearch;
    private javax.swing.JTextField txtTPNo;
    // End of variables declaration//GEN-END:variables

	private void loadPartSuppliers() {

		try {

			jTablepro.removeAll();
			jTablepro.repaint();
			jTablepro.revalidate();
			DefaultTableModel dtm = (DefaultTableModel) jTablepro.getModel();
			dtm.getDataVector().removeAllElements();
			ResultSet sr = DB_connection.search("select * from Part_supplier");

			while (sr.next()) {

				Vector v = new Vector();
				v.add(sr.getString("idPart_supplier"));
				v.add(sr.getString("Email"));
				v.add(sr.getString("Company_name"));
				v.add(sr.getString("Tel_number"));
				v.add(sr.getString("Address"));

				dtm.addRow(v);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	private void clearAll() {
		txtCompantName.setText("");
		txtEmail.setText("");
		txtTPNo.setText("");
		txtAddress.setText("");
	}

}
